#set up properties
PROJECT_ID: valid-might-365117

server:
    port: ${DEFAULT_PORT:80}

spring:
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, firestore
            label: master
        gcp:
            credentials:
                location: classpath:key.json  
            firestore:
                project-id: ${PROJECT_ID:valid-might-365117}
                enabled: true


gcp:
    firestore:
        collections:
            parent:
                prefix: Medical-Management-System/data
                customerLoginData: Customer-Login-Data