#set up properties
PROJECT_ID: valid-might-365117

server:
    port: ${DEFAULT_PORT:80}

spring:
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, firestore
            label: master
        gcp:
            credentials:
                location: classpath:key.json  
            firestore:
                project-id: ${PROJECT_ID:valid-might-365117}
                enabled: true
    mail:
        host: smtp.gmail.com
        port: 465
        username: gsubhankar2018@gmail.com
        password: ihvfxhdgqwmtmkzi
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        protocols: TLSv1.2
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory


gcp:
    firestore:
        collections:
            parent:
                prefix: Medical-Management-System/data
                customerLoginData: Customer-Login-Data
                userData: customer-details