#set up properties
PROJECT_ID: golden-pillar-371210

server:
    port: ${DEFAULT_PORT:80}

spring:
    main:
        allow-bean-definition-overriding: true

    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, firestore
            label: master
        gcp:
            project-id: ${PROJECT_ID:golden-pillar-371210}
            pubsub:
                health:
                    timeout-mills: 20000
            credentials:
                location: classpath:key.json  
            firestore:
                project-id: ${PROJECT_ID:golden-pillar-371210}
                enabled: true
    mail:
        host: smtp.gmail.com
        port: 465
        username: gsubhankar2018@gmail.com
        password: ihvfxhdgqwmtmkzi
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        protocols: TLSv1.2
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory


gcp:
    firestore:
        collections:
            parent:
                prefix: Medical-Management-System/data
                customerLoginData: Customer-Login-Data
                userData: customer-details
    pubsub:
        project-id: golden-pillar-371210
        topic:
            mms: connector-service-mms-topic
        subscription:
            customer_reg: connector-service-customer-reg-subscriber
